[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[[bin]]
name = "codegen"
required-features = ["cli"]

[dependencies]
async-sse = "5.1.0"
chrono = { version = "0.4.41", features = ["serde"] }
crux_core.workspace = true
crux_http.workspace = true
crux_time.workspace = true
facet = { version = "0.28.0", features = ["chrono"] }
futures = "0.3.31"
log = { version = "0.4.27", optional = true }
pretty_env_logger = { version = "0.5.0", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.141"
url = "2.5.4"

[dev-dependencies]
insta = { version = "1.43.1", features = ["yaml"] }

# not wasm
[target.'cfg(not(target_family = "wasm"))'.dependencies]
rand = { version = "0.9.2", features = ["os_rng"] }
uniffi = "0.29.4"

# wasm32-unknown-unknown, but not wasm32-wasip2
[target.'cfg(any(target_family = "wasm", not(all(target_os = "wasi", target_env = "p2"))))'.dependencies]
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"

# wasm32-wasip2
[target.'cfg(all(target_os = "wasi", target_env = "p2"))'.dependencies]
crux_core = { workspace = true, features = ["facet_typegen"] }
crux_http = { workspace = true, features = ["facet_typegen"] }
wit-bindgen = "0.43.0"

[features]
cli = ["crux_core/cli", "dep:log", "dep:pretty_env_logger"]
facet_typegen = ["crux_core/facet_typegen"]
